### ISSUE TITLE
Incorrect set data in ROBYN_MAX_PAYLOAD_SIZE

### ISSUE THREAD

**Issue by mirecl** [sansyrox/robyn#473]
### Bug Description

My app.py:
```python
from robyn import Robyn

app = Robyn(__file__)

@app.get("/")
async def h(request):
    return {"message":"Hello, world!"}

app.start()
```

Run with env var **ROBYN_MAX_PAYLOAD_SIZE**:
```bash
ROBYN_MAX_PAYLOAD_SIZE=100r000 python app.py --log-level=DEBUG
```
Get exception start service and as a result - dead robyn(
```bash
INFO:robyn.logger:Starting server at 127.0.0.1:8080
INFO:robyn.logger:Press Ctrl + C to stop 

DEBUG:robyn.server:The number of workers is 1
INFO:actix_server.builder:Starting 1 workers
INFO:actix_server.server:Actix runtime found; starting in Actix runtime
thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', src/server.rs:173:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-server-2.1.1/src/worker.rs:472:27
```

Exception:
https://github.com/sansyrox/robyn/blob/main/src/server.rs#L172-L175

Feature support ROBYN_MAX_PAYLOAD_SIZE add in https://github.com/sansyrox/robyn/issues/463 (release 0.27.0)

 **Expected Behavior - get error and robyn finished work:**
 ```bash
INFO:robyn.logger:Starting server at 127.0.0.1:8080
INFO:robyn.logger:Press Ctrl + C to stop 

Process Process-1:
Traceback (most recent call last):
  File "/Users/16557938/Desktop/robyn/venv/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/16557938/Desktop/robyn/venv/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/16557938/Desktop/robyn/venv/lib/python3.8/site-packages/robyn/processpool.py", line 189, in spawn_process
    server.start(socket, workers)
ValueError: Failed to parse environment variable ROBYN_MAX_PAYLOAD_SIZE - invalid digit found in string
(venv) bash % 
```bash


### Steps to Reproduce

1. Source code app.py see above;
2. ROBYN_MAX_PAYLOAD_SIZE=100r000 python app.py --log-level=DEBUG.

### Your operating system

MacOS

### Your Python version (`python --version`)

3.8

### Your Robyn version

latest

### Additional Info

1. Preparing PR for fix bug
2. Propose to move the entire configuration into a separate file (config.rs) at the same level as server.rs.
3. Load configuration with https://github.com/mehcode/config-rs or https://github.com/greyblake/envconfig-rs or ...
4. Found a problem - if an exception occurs in thread https://github.com/sansyrox/robyn/blob/main/src/server.rs#L110 . Robyn stop responding and dead(

**Comment by sansyrox** [comment]
@mirecl , thank you for creating this issue.

What do you mean by these ? What value will these add?
> Propose to move the entire configuration into a separate file (config.rs) at the same level as server.rs.
Load configuration with https://github.com/mehcode/config-rs or https://github.com/greyblake/envconfig-rs or ...

**Comment by mirecl** [comment]
@sansyrox, later I will open a new discussion on github.
